### ISSUE TITLE
Crash when start session

### ISSUE THREAD

**Issue by songloimr** [GetStream/webrtc-in-jetpack-compose#11]
```
No implementation found for long org.webrtc.SoftwareVideoDecoderFactory.nativeCreateDecoder(long, org.webrtc.VideoCodecInfo) (tried Java_org_webrtc_SoftwareVideoDecoderFactory_nativeCreateDecoder and Java_org_webrtc_SoftwareVideoDecoderFactory_nativeCreateDecoder__JLorg_webrtc_VideoCodecInfo_2)
java.lang.UnsatisfiedLinkError: No implementation found for long org.webrtc.SoftwareVideoDecoderFactory.nativeCreateDecoder(long, org.webrtc.VideoCodecInfo) (tried Java_org_webrtc_SoftwareVideoDecoderFactory_nativeCreateDecoder and Java_org_webrtc_SoftwareVideoDecoderFactory_nativeCreateDecoder__JLorg_webrtc_VideoCodecInfo_2)
	at org.webrtc.SoftwareVideoDecoderFactory.nativeCreateDecoder(Native Method)
	at org.webrtc.SoftwareVideoDecoderFactory.createDecoder(SoftwareVideoDecoderFactory.java:29)
	at org.webrtc.DefaultVideoDecoderFactory.createDecoder(DefaultVideoDecoderFactory.java:43)
```
Android: 11 HiOS, 13 ColorOS

**Comment by sergiooreh** [comment]
Same

**Comment by dontbesatisfied** [comment]
me too.

**Comment by xxfast** [comment]
Same here. 
```
16272-16492 .sample.compose         io....mple.compose  E  No implementation found for long org.webrtc.SoftwareVideoDecoderFactory.nativeCreateDecoder(long, org.webrtc.VideoCodecInfo) (tried Java_org_webrtc_SoftwareVideoDecoderFactory_nativeCreateDecoder and Java_org_webrtc_SoftwareVideoDecoderFactory_nativeCreateDecoder__JLorg_webrtc_VideoCodecInfo_2) - is the library loaded, e.g. System.loadLibrary?
16272-16492 System.err              io....mple.compose  W  java.lang.UnsatisfiedLinkError: No implementation found for long org.webrtc.SoftwareVideoDecoderFactory.nativeCreateDecoder(long, org.webrtc.VideoCodecInfo) (tried Java_org_webrtc_SoftwareVideoDecoderFactory_nativeCreateDecoder and Java_org_webrtc_SoftwareVideoDecoderFactory_nativeCreateDecoder__JLorg_webrtc_VideoCodecInfo_2) - is the library loaded, e.g. System.loadLibrary?
16272-16492 System.err              io....mple.compose  W  	at org.webrtc.SoftwareVideoDecoderFactory.nativeCreateDecoder(Native Method)
16272-16492 System.err              io....mple.compose  W  	at org.webrtc.SoftwareVideoDecoderFactory.createDecoder(SoftwareVideoDecoderFactory.java:29)
16272-16492 System.err              io....mple.compose  W  	at org.webrtc.DefaultVideoDecoderFactory.createDecoder(DefaultVideoDecoderFactory.java:43)
16272-16492 rtc                     io....mple.compose  E  #
                                                           # Fatal error in: gen/jni_headers/sdk/android/generated_video_jni/../../../../../../../../home/kanat/webrtc/src/sdk/android/src/jni/jni_generator_helper.h, line 105
                                                           # last system error: 0
                                                           # Check failed: !env->ExceptionCheck()
                                                           # 
16272-16492 libc                    io....mple.compose  A  Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 16492 (DecodingQueue -), pid 16272 (.sample.compose)
16272-16380 Call:WebRTC             io....mple.compose  I  (worker_thread - 16380:1636) [onLogMessage] label: probe_bitrate_estimator.cc, message: (line 164): Probing successful [cluster id: 4] [send: 5374 bytes / 10 ms = 4299200 bps ] [receive: 5190 bytes / 10 ms = 4152 kbps]
16272-16380 Call:WebRTC             io....mple.compose  I  (worker_thread - 16380:1636) [onLogMessage] label: probe_bitrate_estimator.cc, message: (line 164): Probing successful [cluster id: 4] [send: 5497 bytes / 12 ms = 3664666 bps ] [receive: 6206 bytes / 11 ms = 4513454 bps]
16272-16380 Call:WebRTC             io....mple.compose  I  (worker_thread - 16380:1636) [onLogMessage] label: probe_bitrate_estimator.cc, message: (line 164): Probing successful [cluster id: 4] [send: 6513 bytes / 15 ms = 3473600 bps ] [receive: 7222 bytes / 15 ms = 3851733 bps]
16595-16595 DEBUG                   pid-16595           A  Cmdline: io.getstream.webrtc.sample.compose
16595-16595 DEBUG                   pid-16595           A  pid: 16272, tid: 16492, name: DecodingQueue -  >>> io.getstream.webrtc.sample.compose <<<
16595-16595 DEBUG                   pid-16595           A        #01 pc 000000000045b670  /data/app/~~ziTqk7lgAwXVk9Egmt4yNw==/io.getstream.webrtc.sample.compose-1OIXdVaDIEXLMFwqdStk7A==/base.apk!libjingle_peerconnection_so.so (offset 0x38000) (BuildId: 0d2f7a27162e2409)
16595-16595 DEBUG                   pid-16595           A        #02 pc 000000000045bd04  /data/app/~~ziTqk7lgAwXVk9Egmt4yNw==/io.getstream.webrtc.sample.compose-1OIXdVaDIEXLMFwqdStk7A==/base.apk!libjingle_peerconnection_so.so (offset 0x38000) (BuildId: 0d2f7a27162e2409)
16595-16595 DEBUG                   pid-16595           A        #03 pc 00000000005606d8  /data/app/~~ziTqk7lgAwXVk9Egmt4yNw==/io.getstream.webrtc.sample.compose-1OIXdVaDIEXLMFwqdStk7A==/base.apk!libjingle_peerconnection_so.so (offset 0x38000) (BuildId: 0d2f7a27162e2409)
16595-16595 DEBUG                   pid-16595           A        #04 pc 00000000009d6890  /data/app/~~ziTqk7lgAwXVk9Egmt4yNw==/io.getstream.webrtc.sample.compose-1OIXdVaDIEXLMFwqdStk7A==/base.apk!libjingle_peerconnection_so.so (offset 0x38000) (BuildId: 0d2f7a27162e2409)
16595-16595 DEBUG                   pid-16595           A        #05 pc 00000000009d8cec  /data/app/~~ziTqk7lgAwXVk9Egmt4yNw==/io.getstream.webrtc.sample.compose-1OIXdVaDIEXLMFwqdStk7A==/base.apk!libjingle_peerconnection_so.so (offset 0x38000) (BuildId: 0d2f7a27162e2409)
16595-16595 DEBUG                   pid-16595           A        #06 pc 0000000000654518  /data/app/~~ziTqk7lgAwXVk9Egmt4yNw==/io.getstream.webrtc.sample.compose-1OIXdVaDIEXLMFwqdStk7A==/base.apk!libjingle_peerconnection_so.so (offset 0x38000) (BuildId: 0d2f7a27162e2409)
16595-16595 DEBUG                   pid-16595           A        #07 pc 0000000000656204  /data/app/~~ziTqk7lgAwXVk9Egmt4yNw==/io.getstream.webrtc.sample.compose-1OIXdVaDIEXLMFwqdStk7A==/base.apk!libjingle_peerconnection_so.so (offset 0x38000) (BuildId: 0d2f7a27162e2409)
16595-16595 DEBUG                   pid-16595           A        #08 pc 0000000000654e9c  /data/app/~~ziTqk7lgAwXVk9Egmt4yNw==/io.getstream.webrtc.sample.compose-1OIXdVaDIEXLMFwqdStk7A==/base.apk!libjingle_peerconnection_so.so (offset 0x38000) (BuildId: 0d2f7a27162e2409)
16595-16595 DEBUG                   pid-16595           A        #09 pc 000000000046ccec  /data/app/~~ziTqk7lgAwXVk9Egmt4yNw==/io.getstream.webrtc.sample.compose-1OIXdVaDIEXLMFwqdStk7A==/base.apk!libjingle_peerconnection_so.so (offset 0x38000) (BuildId: 0d2f7a27162e2409)
16595-16595 DEBUG                   pid-16595           A        #10 pc 000000000046cbd4  /data/app/~~ziTqk7lgAwXVk9Egmt4yNw==/io.getstream.webrtc.sample.compose-1OIXdVaDIEXLMFwqdStk7A==/base.apk!libjingle_peerconnection_so.so (offset 0x38000) (BuildId: 0d2f7a27162e2409)
 1627-2335  AppOps                  pid-1627            E  Operation not started: uid=10813 pkg=io.getstream.webrtc.sample.compose(null) op=CAMERA
 1627-2185  AppOps                  pid-1627            E  Operation not started: uid=10813 pkg=io.getstream.webrtc.sample.compose(null) op=RECORD_AUDIO
 1627-2185  AppOps                  pid-1627            E  Operation not started: uid=10813 pkg=io.getstream.webrtc.sample.compose(null) op=RECORD_AUDIO
```

**Comment by meysam-azadmehr** [comment]
@xxfast @songloimr  @dontbesatisfied 
 update version of webrtc in version catalog .i upgrade webrtc from 1.3.0 to 1.3.6 . and fix this
